### ISSUE TITLE
Highlight disappears when background change

### ISSUE THREAD

**Issue by pitakill** [lcheylus/overlength.nvim#1]
Hi, thank you for this plugin. It works great, but I think I found a bug.

When I change the background (dark/light) the highlight disappears. I just change the background with a basic `:set background=light` or `:set background=dark` and I also see the same behavior when a `:colorscheme licius` occurs. I lack the vim /nvim knowledge to debug this, but I can help with the Lua stuff.

**Comment by lcheylus** [comment]
It's the normal behavior for Vim/Neovim when you set `background` option or change colorscheme :

- overlength.nvim plugin sets `OverLength` hightlight to display too long lines (use of Neovim API `nvim_set_hl` function ~ `highlight` command for Vim), see code in `lua/overlength/init.lua` , function `setup`
- when you set `background` option or change colorscheme, highlight groups will change (see [Vim docs for `background` option ](https://neovim.io/doc/user/options.html#'background')) => `OverLength` highlight for plugin is no more defined.

If you want to change `background` option or set a colorscheme, you have to call `overlength.setup()` function after.
